name: dev branch auto ci process script # 워크플로우 이름

on: # 워크플로우 실행 조건
  push:
    branches: [dev] # dev 브랜치에 push될 때 실행

jobs: # 실행할 작업 정의
  deploy: # 배포 작업
    name: deploy
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 실행

    steps: # 실행할 단계들
      - name: excuting remote ssh commands # 원격 서버에 SSH로 접속하여 명령어 실행
        uses: appleboy/ssh-action@v0.1.6 # SSH 액션 사용
        with:
          host: ${{ secrets.REMOTE_IP }} # EC2 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # EC2 사용자 이름
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # SSH 개인키
          port: ${{ secrets.REMOTE_SSH_PORT }} # SSH 포트 (기본 22)
          script: | # 실행할 명령어들
            cd /home/ubuntu/Frontend  # 프로젝트 디렉토리로 이동
            git pull origin main  # 최신 코드 가져오기
            pm2 kill  # 실행 중인 프로세스 종료
            npm i --force  # 의존성 설치
            npm run build  # 프로젝트 빌드
            pm2 start npm --name "frontend" -- start  # Next.js 서버 시작
